<div class="text-white">
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    Stop trying to control. <br>
    <div class="size-20 cursor-pointer bg-black" wire:click.prevent="$dispatch('openModal', { component: 'viewer', arguments: { task: 58 }})"></div>
</div>
